# Generated by Django 4.2.27 on 2026-01-24 23:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "collection_id",
                    models.BigIntegerField(
                        help_text="Unique 9-digit collection identifier",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(100000000),
                            django.core.validators.MaxValueValidator(999999999),
                        ],
                    ),
                ),
                ("name", models.CharField(default="Untitled Collection", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="IdentifierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="URL pattern with {id} placeholder, e.g., https://www.inaturalist.org/observations/{id}",
                        max_length=500,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Identifier Type",
                "verbose_name_plural": "Identifier Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prompt", models.TextField()),
                ("embedding_name", models.CharField(max_length=255)),
                ("k", models.PositiveIntegerField(default=3)),
                ("result_references", models.JSONField(default=list)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to="search.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History Entry",
                "verbose_name_plural": "Search History Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["collection", "-created_at"], name="search_sear_collect_61d067_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identifiers",
                        to="search.collection",
                    ),
                ),
                (
                    "identifier_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identifiers",
                        to="search.identifiertype",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier_type__name", "value"],
                "unique_together": {("collection", "identifier_type", "value")},
            },
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["collection_id"], name="search_coll_collect_420921_idx"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["owner", "-updated_at"], name="search_coll_owner_i_8371ca_idx"
            ),
        ),
    ]
