# Generated by Django 4.2.27 on 2026-01-24 23:34

from django.db import migrations


def create_identifier_types(apps, schema_editor):
    """Create default identifier types for external systems."""
    IdentifierType = apps.get_model('search', 'IdentifierType')

    identifier_types = [
        {
            'code': 'inat',
            'name': 'iNaturalist',
            'url_pattern': 'https://www.inaturalist.org/observations/{id}',
            'description': 'iNaturalist observation ID'
        },
        {
            'code': 'mo',
            'name': 'Mushroom Observer',
            'url_pattern': 'https://mushroomobserver.org/observations/{id}',
            'description': 'Mushroom Observer observation ID'
        },
        {
            'code': 'genbank',
            'name': 'GenBank',
            'url_pattern': 'https://www.ncbi.nlm.nih.gov/nuccore/{id}',
            'description': 'GenBank accession number'
        },
        {
            'code': 'mycobank',
            'name': 'MycoBank',
            'url_pattern': 'https://www.mycobank.org/page/Name%20details%20page/{id}',
            'description': 'MycoBank taxon ID'
        },
        {
            'code': 'indexfungorum',
            'name': 'Index Fungorum',
            'url_pattern': 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID={id}',
            'description': 'Index Fungorum record ID'
        },
    ]

    for it_data in identifier_types:
        IdentifierType.objects.create(**it_data)


def reverse_identifier_types(apps, schema_editor):
    """Remove seeded identifier types."""
    IdentifierType = apps.get_model('search', 'IdentifierType')
    IdentifierType.objects.filter(
        code__in=['inat', 'mo', 'genbank', 'mycobank', 'indexfungorum']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_collections_feature"),
    ]

    operations = [
        migrations.RunPython(create_identifier_types, reverse_identifier_types),
    ]
