# Generated by Django 4.2.27 on 2026-01-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_seed_identifier_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="notes",
            field=models.TextField(
                blank=True, default="", help_text="Collection-level notes/metadata"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Working taxonomic description text for searching"
            ),
        ),
    ]
