# Generated by Django 4.2.27 on 2026-02-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_fungarium_identifier"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="externalidentifier",
            unique_together={("collection", "identifier_type", "value", "fungarium_code")},
        ),
    ]
