# Generated by Django 4.2.27 on 2026-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_collection_nomenclature_embargo_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="event_type",
            field=models.CharField(
                choices=[("search", "Search"), ("nomenclature_change", "Nomenclature Change")],
                default="search",
                help_text="Type of history event",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="nomenclature",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nomenclature value at time of change (for nomenclature_change events)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="embedding_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
