# Generated by Django 4.2.27 on 2026-02-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_searchhistory_event_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="flagged_by",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of user IDs who flagged this collection as inappropriate",
            ),
        ),
    ]
