# Generated by Django 4.2.27 on 2026-02-16 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0008_collection_flagged_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Admin-hidden collection: excluded from indexing, read-only for owner",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="hidden_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who hid this collection",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
