# Generated by Django 4.2.27 on 2026-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0009_collection_hidden_collection_hidden_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="receive_admin_summary",
            field=models.BooleanField(default=False, help_text="Receive daily admin summary email"),
        ),
    ]
