# Generated by Django 4.2.27 on 2026-02-18 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0011_usersettings_results_per_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="feature_max_df",
            field=models.FloatField(
                default=1.0,
                help_text="Maximum document frequency fraction for feature terms",
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="feature_min_df",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimum document frequency for feature terms",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="feature_top_n",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Number of top features to return from the classifier",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="nomenclature_limit",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Maximum results for nomenclature pattern search",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="default_k",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Default number of search results",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="feature_max_tree_depth",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum depth for feature tree display",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
