# Generated by Django 4.2.27 on 2026-03-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0012_usersettings_feature_max_df_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        default="spores",
                        help_text="Feature name (e.g., spores, basidia, cystidia)",
                        max_length=100,
                    ),
                ),
                (
                    "is_2d",
                    models.BooleanField(
                        default=True,
                        help_text="True for 2D measurements (length x width), False for 1D (length only)",
                    ),
                ),
                (
                    "report_q",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include Q (length/width ratio) in the formatted output",
                    ),
                ),
                (
                    "measurements",
                    models.JSONField(
                        default=list,
                        help_text='Raw measurements: [{"length": 8.5, "width": 6.5}, ...]',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_sets",
                        to="search.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Set",
                "verbose_name_plural": "Measurement Sets",
                "ordering": ["feature"],
                "unique_together": {("collection", "feature")},
            },
        ),
    ]
