# Generated by Django 4.2.27 on 2026-03-12 17:28

from django.db import migrations, models


INITIAL_UNITS = [
    ('nm', 10),
    ('\u00b5m', 20),
    ('mm', 30),
    ('cm', 40),
    ('m', 50),
    ('km', 60),
]


def populate_units(apps, schema_editor):
    MeasurementUnit = apps.get_model('search', 'MeasurementUnit')
    for symbol, sort_order in INITIAL_UNITS:
        MeasurementUnit.objects.get_or_create(
            symbol=symbol,
            defaults={'sort_order': sort_order},
        )


def depopulate_units(apps, schema_editor):
    MeasurementUnit = apps.get_model('search', 'MeasurementUnit')
    symbols = [s for s, _ in INITIAL_UNITS]
    MeasurementUnit.objects.filter(symbol__in=symbols).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0013_measurementset"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Display symbol (e.g., \u00b5m, mm, nm)", max_length=20, unique=True
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order in the dropdown (ascending)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Unit",
                "verbose_name_plural": "Measurement Units",
                "ordering": ["sort_order", "symbol"],
            },
        ),
        migrations.AddField(
            model_name="measurementset",
            name="unit",
            field=models.CharField(
                default="\u00b5m", help_text="Unit of measurement (e.g., \u00b5m, mm, nm)", max_length=20
            ),
        ),
        migrations.RunPython(populate_units, depopulate_units),
    ]
