# Generated by Django 4.2.27 on 2026-04-26 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0015_add_default_experiment_to_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_additions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_projects",
                        to="search.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection–Project membership",
                "verbose_name_plural": "Collection–Project memberships",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        through="search.CollectionProject",
                        to="search.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["creator__username", "slug"],
                "unique_together": {("creator", "slug")},
            },
        ),
        migrations.CreateModel(
            name="CollectionProjectRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("removed_at", models.DateTimeField(auto_now_add=True)),
                ("original_added_at", models.DateTimeField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_removals",
                        to="search.collection",
                    ),
                ),
                (
                    "original_added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_removals_as_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_removals",
                        to="search.project",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_removals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection–Project removal log",
                "verbose_name_plural": "Collection–Project removal logs",
                "ordering": ["-removed_at"],
            },
        ),
        migrations.AddField(
            model_name="collectionproject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_projects",
                to="search.project",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="default_projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects that new collections are automatically added to. Does not apply retroactively to existing collections.",
                related_name="default_for_users",
                to="search.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionproject",
            unique_together={("collection", "project")},
        ),
    ]
