# Generated by Django 4.2.27 on 2026-04-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0016_collectionproject_project_collectionprojectremoval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
