# Generated by Django 4.2.27 on 2026-04-27 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0017_project_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNotesLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diff",
                    models.TextField(help_text="Unified diff of the notes change (old → new)."),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_notes_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_log",
                        to="search.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project notes log entry",
                "verbose_name_plural": "Project notes log entries",
                "ordering": ["-changed_at"],
            },
        ),
    ]
