# Generated by Django 4.2.27 on 2026-05-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0021_update_cbs_url_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="identifiertype",
            name="actions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
