"""
Publication registry for managing ingestion source configurations.

Two related tables:

- ``JOURNALS`` — one row per real-world journal, keyed by a stable
  opaque slug.  Owns the journal-level facts: display name, official
  website, ISSN(s), publisher, historical-name aliases.
- ``SOURCES`` — one row per ingestion mechanism (RSS / PMC /
  Crossref / local mirror) for a given journal.  Each row's
  ``journal`` field is a foreign-key slug into JOURNALS.

See ``docs/publications_metadata_consolidation.md``.
"""

import sys
from typing import Any, Dict, List, Optional, TypedDict

if sys.version_info >= (3, 11):
    from typing import NotRequired
else:  # pragma: no cover — only one branch is exercised at runtime
    from typing_extensions import NotRequired


class JournalEntry(TypedDict, total=False):
    """One row of the ``JOURNALS`` table.

    ``name`` is the only required field — every journal must
    have a display name.  All other fields are NotRequired
    because the data is genuinely heterogeneous (some journals
    have ISSN, some ISBN, some neither; eissn is electronic-
    only or absent on print-only journals).
    """
    name:      str
    aliases:   NotRequired[List[str]]
    address:   NotRequired[str]   # journal homepage (NOT scrape URL)
    issn:      NotRequired[str]
    eissn:     NotRequired[str]
    isbn:      NotRequired[str]   # for book-like references
    doi:       NotRequired[str]   # journal-DOI, not article DOI
    publisher: NotRequired[str]
    abbrev:    NotRequired[str]   # ISO 4 abbreviation


class SourceEntry(TypedDict, total=False):
    """One row of the ``SOURCES`` table — a single ingestion
    mechanism for some journal.  ``journal`` (the FK slug into
    JOURNALS), ``source``, and ``ingestor_class`` are the
    operational requirements.
    """
    journal:           str   # FK slug into JOURNALS
    name:              str   # legacy display name (kept for migration window)
    source:            str
    address:           NotRequired[str]   # scrape endpoint (NOT homepage)
    ingestor_class:    str
    local_path:        NotRequired[str]
    local_path_prefix: NotRequired[str]
    url_prefix:        NotRequired[str]
    rate_limit_min_ms: NotRequired[int]
    rate_limit_max_ms: NotRequired[int]
    issn:              NotRequired[str]
    eissn:             NotRequired[str]


# Publishers / source-providers that pre-refactor SOURCES rows
# tacked on as ``" (Publisher)"`` parentheticals to disambiguate
# multi-ingestor journals.  Stripping them is what causes legacy
# compound names like ``"Journal of Fungi (PMC)"`` to resolve to
# the same canonical journal as ``"Journal of Fungi"``.
_KNOWN_PUBLISHER_SUFFIXES = (
    'PMC',
    'Taylor & Francis',
    'Internet Archive',
)


def strip_publisher_suffix(name: str) -> str:
    """Strip a trailing ``" (Publisher)"`` when the publisher is a
    known disambiguator.  Idempotent; conservative — non-publisher
    parentheticals like ``"Mycotaxon (n.s.)"`` pass through
    unchanged.

    Also imported by ``bin/scaffold_journals.py`` (one source of
    truth for the recognised-publisher list).
    """
    stripped = name.strip()
    for suffix in _KNOWN_PUBLISHER_SUFFIXES:
        marker = f'({suffix})'
        if stripped.endswith(marker):
            return stripped[:-len(marker)].strip()
    return stripped


class PublicationRegistry:
    """
    Registry for publication source configurations.

    This class manages all predefined publication sources, their configurations,
    and provides methods to access publication information.
    """

    # Default configuration values for all publications
    DEFAULTS: Dict[str, Any] = {
        'rate_limit_min_ms': 1000,  # Minimum delay between requests (milliseconds)
        'rate_limit_max_ms': 5000,  # Maximum delay between requests (milliseconds)
    }

    # JOURNALS — one row per real-world journal, keyed by stable
    # opaque slug.  Generated by ``bin/scaffold_journals.py`` against
    # current SOURCES + Crossref ``/journals/{issn}`` enrichment,
    # then hand-edited.  ``address`` and ``aliases`` start empty;
    # phase 3 of the consolidation migrates aliases here from
    # JOURNAL_NAME_ALIASES; ``address`` gets filled in by hand from
    # each journal's official site.
    JOURNALS: Dict[str, JournalEntry] = {
        'annals-of-the-missouri-botanical-garden': {
            'name':      'Annals of the Missouri Botanical Garden',
            'address':   'https://annals.mobot.org/index.php/annals',
            'publisher': 'Missouri Botanical Garden Press',
            'issn':      '0026-6493',
            'aliases': [
                'Ann. Missouri Bot. Gard.',
                # Extraction artefacts from earlier mykoweb-citation
                # parsing — the regex sometimes captured a citation
                # fragment + journal name together; keep them as
                # aliases so any straggler doc rolls up correctly.
                'and Leucophlebs in North America. Ann. Missouri Bot. Gard.',
                'Gymnomyces, and Macowanites in North America. Ann. Missouri Bot. Gard.',
                'in North America. Ann. Missouri Bot. Gard.',
            ],
        },
        'cryptogamie-mycologie': {
            'name':      'Cryptogamie, Mycologie',  # canonical form
            'address':   'https://sciencepress.mnhn.fr/en/periodiques/mycologie',
            'publisher': "BioOne (Museum National d'Histoire Naturelle, Paris, France)",
            'issn':      '0181-1584',
            'eissn':     '1776-100X',
            'aliases': [
                'Cryptogamie. Mycologie',
                'Cryptogamie Mycologie',
            ],
        },
        'current-medical-mycology': {
            'name':      'Current Medical Mycology',
            'address':   'http://cmm.mazums.ac.ir/',
            'publisher': 'Mazandaran University of Medical Sciences',
            'eissn':     '2423-3420',
        },
        'frontiers-in-fungal-biology': {
            'name':      'Frontiers in Fungal Biology',
            'address':   'https://www.frontiersin.org/journals/fungal-biology',
            'publisher': 'Frontiers Media S.A.',
            'eissn':     '2673-6128',
        },
        'fungal-biology-and-biotechnology': {
            'name':      'Fungal Biology and Biotechnology',
            'address':   'https://fungalbiolbiotech.biomedcentral.com/',
            'publisher': 'BioMed Central (Springer Nature)',
            'eissn':     '2054-3085',
        },
        'fungal-systematics-and-evolution': {
            'name':      'Fungal Systematics and Evolution',
            'address':   'https://fuse-journal.org/',
            'publisher': 'Westerdijk Fungal Biodiversity Institute',
            'issn':      '2589-3823',
            'eissn':     '2589-3831',
        },
        'ima-fungus': {
            'name':      'IMA Fungus',
            'address':   'https://imafungus.pensoft.net/',
            'publisher': 'Pensoft Publishers',
            'issn':      '2210-6340',
            'eissn':     '2210-6359',
        },
        'journal-of-fungi': {
            'name':      'Journal of Fungi',
            'address':   'https://www.mdpi.com/journal/jof',
            'publisher': 'MDPI AG',
            'eissn':     '2309-608X',
        },
        'journal-of-mycology': {
            'name':      'The Journal of Mycology',
            'address':   'https://www.jstor.org/journal/jmycology',
            'publisher': 'JSTOR',
            'issn':      '1052-0368',
            'aliases': [
                'Journal of Mycology',  # without leading "The"
            ],
        },
        'medical-mycology-case-reports': {
            'name':      'Medical Mycology Case Reports',
            'address':   'https://www.sciencedirect.com/journal/medical-mycology-case-reports',
            'publisher': 'International Society for Human and Animal Mycology',
            'eissn':     '2211-7539',
        },
        'mycobiology': {
            'name':      'Mycobiology',
            'address':   'https://www.tandfonline.com/journals/tmyb20',
            'publisher': 'Korean Society of Mycology',
            'eissn':     '2092-9323',
        },
        'mycokeys': {
            'name':      'MycoKeys',
            'address':   'https://mycokeys.pensoft.net/',
            'publisher': 'Pensoft Publishers',
            'issn':      '1314-4057',
            'eissn':     '1314-4049',
        },
        'mycologia': {
            'name':      'Mycologia',
            'address':   'https://www.tandfonline.com/journals/umyc20',
            'publisher': 'Informa UK (Taylor & Francis)',
            'issn':      '0027-5514',
            'eissn':     '1557-2536',
        },
        'mycology': {
            'name':      'Mycology: An International Journal on Fungal Biology',
            'address':   'https://www.tandfonline.com/journals/tmyc20',
            'publisher': 'Informa UK (Taylor & Francis)',
            'issn':      '2150-1203',
            'eissn':     '2150-1211',
            'aliases': [
                'Mycology',  # bare short form; ~872 docs in skol_dev
            ],
        },
        'mycoscience': {
            'name':      'Mycoscience',
            'address':   'https://mycoscience.org/',
            'publisher': 'The Mycological Society of Japan',
            'issn':      '1340-3540',
            'eissn':     '1618-2545',
        },
        'mycosphere': {
            'name':      'Mycosphere',
            'address':   'https://www.mycosphere.org/',
            'publisher': 'Maximum Academic Press',
            'eissn':     '2077-7000',
            'aliases': [
                'mycosphere',  # lowercase form; ~873 docs in skol_dev
            ],
        },
        'mycotaxon': {
            'name':      'Mycotaxon',
            'address':   'https://www.mycotaxon.com/',
            'publisher': 'Mycotaxon, Ltd.',  # Crossref reports BHL (deposit agent); real publisher is Mycotaxon, Ltd.
            'issn':      '0093-4666',
            'eissn':     '2154-8889',
        },
        'open-access-journal-of-mycology-mycological-sciences': {
            'name':      'Open Access Journal of Mycology & Mycological Sciences',
            'address':   'https://medwinpublishers.com/OAJMMS/',
            'publisher': 'Medwin Publishers',
            'issn':      '2689-7822',
            'aliases': [
                'Open Access Journal of Mycology &amp; Mycological Sciences',
            ],
        },
        'persoonia': {
            'name':      'Persoonia',  # canonical short form
            'address':   'https://persoonia.org/',
            'publisher': 'Westerdijk Fungal Biodiversity Institute',
            'issn':      '0031-5850',
            'eissn':     '1878-9080',
            'aliases': [
                'Persoonia - Molecular Phylogeny and Evolution of Fungi',
            ],
        },
        'studies-in-mycology': {
            'name':      'Studies in Mycology',
            'address':   'https://www.studiesinmycology.org/',
            'publisher': 'Westerdijk Fungal Biodiversity Institute',
            'issn':      '0166-0616',
            'eissn':     '1872-9797',
        },
        'sydowia': {
            'name':      'Sydowia',
            'address':   'https://www.sydowia.at/',
            'publisher': 'Verlag Ferdinand Berger & Söhne',
            'issn':      '0082-0598',
            # Crossref 404s on this ISSN — fields filled in by hand.
            'aliases': [
                'Sydowia Beih.',
            ],
        },
    }

    # ``JOURNAL_NAME_ALIASES`` lived here pre-phase-3 as a flat dict
    # of variant → canonical journal names.  Phase 3 migrated each
    # entry into the ``aliases`` list of its owning ``JOURNALS`` row;
    # consumers go through ``normalize_journal_name()`` (which now
    # scans ``JOURNALS[*].aliases``) instead.

    # Robots.txt URLs for each source
    ROBOTS_URLS: Dict[str, str] = {
        'crossref': 'https://api.crossref.org/robots.txt',
        'ingenta': 'https://www.ingentaconnect.com/robots.txt',
        'mdpi': 'https://www.mdpi.com/robots.txt',
        'medwin-publishers': 'https://medwinpublishers.com/robots.txt',
        'mykoweb-journals': 'https://mykoweb.com/robots.txt',
        'mykoweb-literature': 'https://mykoweb.com/robots.txt',
        'mykoweb-caf': 'https://mykoweb.com/robots.txt',
        'mykoweb-crepidotus': 'https://mykoweb.com/robots.txt',
        'mykoweb-oldbooks': 'https://mykoweb.com/robots.txt',
        'mykoweb-gsmnp': 'https://mykoweb.com/robots.txt',
        'mykoweb-pholiota': 'https://mykoweb.com/robots.txt',
        'mykoweb-misc': 'https://mykoweb.com/robots.txt',
        'mycosphere': 'https://mycosphere.org/robots.txt',
        'pensoft': 'https://pensoft.net/robots.txt',
        'mycology-taylor-francis': 'https://www.tandfonline.com/robots.txt',
        'internet-archive': 'https://archive.org/robots.txt',
        'pmc': 'https://www.ncbi.nlm.nih.gov/robots.txt',
    }

    # Publication source configurations
    SOURCES: Dict[str, Dict[str, Any]] = {
        'fuse-rss': {
            'name': 'Fungal Systematics and Evolution',
            'journal': 'fungal-systematics-and-evolution',
            'address': 'https://api.ingentaconnect.com/content/wfbi/fuse',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'rss',
            'rss_url': 'https://api.ingentaconnect.com/content/wfbi/fuse?format=rss',
        },
        'fuse': {
            'name': 'Fungal Systematics and Evolution',
            'journal': 'fungal-systematics-and-evolution',
            'address': 'https://api.ingentaconnect.com/content/wfbi/fuse',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'index',
            'index_url': 'https://api.ingentaconnect.com/content/wfbi/fuse?format=index',
        },
        'fuse-pmc': {
            'name': 'Fungal Systematics and Evolution (PMC)',
            'journal': 'fungal-systematics-and-evolution',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Fungal Syst Evol"[journal]',
            'issn': '2589-3823',
            'eissn': '2589-3831',
        },
        'persoonia-pmc': {
            'name': 'Persoonia (PMC)',
            'journal': 'persoonia',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Persoonia"[journal]',
            'issn': '0031-5850',
            'eissn': '1878-9080',
        },
        'sim-pmc': {
            'name': 'Studies in Mycology (PMC)',
            'journal': 'studies-in-mycology',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Stud Mycol"[journal]',
            'issn': '0166-0616',
            'eissn': '1872-9797',
        },
        'imafungus-pmc': {
            'name': 'IMA Fungus (PMC)',
            'journal': 'ima-fungus',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"IMA Fungus"[journal]',
            'issn': '2210-6340',
            'eissn': '2210-6359',
        },
        'mycokeys-pmc': {
            'name': 'MycoKeys (PMC)',
            'journal': 'mycokeys',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"MycoKeys"[journal]',
            'issn': '1314-4057',
            'eissn': '1314-4049',
        },
        'jof-pmc': {
            'name': 'Journal of Fungi (PMC)',
            'journal': 'journal-of-fungi',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"J Fungi (Basel)"[journal]',
            'eissn': '2309-608X',
        },
        'mycoscience-pmc': {
            'name': 'Mycoscience (PMC)',
            'journal': 'mycoscience',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Mycoscience"[journal]',
            'issn': '1340-3540',
            'eissn': '1618-2545',
        },
        'mycology-pmc': {
            'name': 'Mycology (PMC)',
            'journal': 'mycology',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Mycology"[journal]',
            'issn': '2150-1203',
            'eissn': '2150-1211',
        },
        'fungal-biol-biotechnol-pmc': {
            'name': 'Fungal Biology and Biotechnology (PMC)',
            'journal': 'fungal-biology-and-biotechnology',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Fungal Biol Biotechnol"[journal]',
            'eissn': '2054-3085',
        },
        'front-fungal-biol-pmc': {
            'name': 'Frontiers in Fungal Biology (PMC)',
            'journal': 'frontiers-in-fungal-biology',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Front Fungal Biol"[journal]',
            'eissn': '2673-6128',
        },
        'mycobiology-pmc': {
            'name': 'Mycobiology (PMC)',
            'journal': 'mycobiology',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Mycobiology"[journal]',
            'eissn': '2092-9323',
        },
        'curr-med-mycol-pmc': {
            'name': 'Current Medical Mycology (PMC)',
            'journal': 'current-medical-mycology',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Curr Med Mycol"[journal]',
            'eissn': '2423-3420',
        },
        'med-mycol-case-rep-pmc': {
            'name': 'Medical Mycology Case Reports (PMC)',
            'journal': 'medical-mycology-case-reports',
            'address': 'https://pmc.ncbi.nlm.nih.gov/',
            'source': 'pmc',
            'ingestor_class': 'PmcIngestor',
            'mode': 'api',
            'journal_search_term': '"Med Mycol Case Rep"[journal]',
            'eissn': '2211-7539',
        },
        'mycotaxon-rss': {
            'name': 'Mycotaxon',
            'journal': 'mycotaxon',
            'address': 'https://api.ingentaconnect.com/content/mtax/mt',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'rss',
            'rss_url': 'https://api.ingentaconnect.com/content/mtax/mt?format=rss',
        },
        'mycotaxon': {
            'name': 'Mycotaxon',
            'journal': 'mycotaxon',
            'address': 'https://api.ingentaconnect.com/content/mtax/mt',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'index',
            'index_url': 'https://api.ingentaconnect.com/content/mtax/mt?format=index',
            'issn': '0093-4666',
            'eissn': '2154-8889',
        },
        'studies-in-mycology': {
            'name': 'Studies in Mycology',
            'journal': 'studies-in-mycology',
            'address': 'https://api.ingentaconnect.com/content/wfbi/sim',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'index',
            'index_url': 'https://api.ingentaconnect.com/content/wfbi/sim?format=index',
        },
        'studies-in-mycology-rss': {
            'name': 'Studies in Mycology',
            'journal': 'studies-in-mycology',
            'address': 'https://api.ingentaconnect.com/content/wfbi/sim',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'rss',
            'rss_url': 'https://api.ingentaconnect.com/content/wfbi/sim?format=rss',
        },
        'persoonia': {
            'name': 'Persoonia',
            'journal': 'persoonia',
            'address': 'https://api.ingentaconnect.com/content/wfbi/pimj',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'index',
            'index_url': 'https://api.ingentaconnect.com/content/wfbi/pimj?format=index',
            'issn': '0031-5850',
            'eissn': '1878-9080',
        },
        'persoonia-rss': {
            'name': 'Persoonia',
            'journal': 'persoonia',
            'address': 'https://api.ingentaconnect.com/content/wfbi/pimj',
            'source': 'ingenta',
            'ingestor_class': 'IngentaIngestor',
            'mode': 'rss',
            'rss_url': 'https://api.ingentaconnect.com/content/wfbi/pimj?format=rss',
        },
        'ingenta-local': {
            'name': 'Ingenta Local BibTeX Files',
            'journal': None,  # Multiple journals
            'address': 'https://www.ingentaconnect.com',
            'source': 'ingenta',
            'ingestor_class': 'LocalIngentaIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/www.ingentaconnect.com',
        },
        'jof-rss': {
            # Currently blocked by technical measures at mdpi.com.
            'blocked': True,
            'name': 'Journal of Fungi',
            'journal': 'journal-of-fungi',
            'address': 'https://www.mdpi.com/journal/jof',
            'source': 'mdpi',
            'ingestor_class': 'MdpiIngestor',
            'mode': 'rss',
            'rss_url': 'https://www.mdpi.com/rss/journal/jof',
            'journal_code': 'jof',
            'issn': '2309-608X',
        },
        'jof': {
            # Currently blocked by technical measures at mdpi.com.
            'blocked': True,
            'name': 'Journal of Fungi',
            'journal': 'journal-of-fungi',
            'address': 'https://www.mdpi.com/journal/jof',
            'source': 'mdpi',
            'ingestor_chttps://doi.org/10.3390/jof5020045lass': 'MdpiIngestor',
            'mode': 'index',
            'index_url': 'https://www.mdpi.com/journal/jof',
            'journal_code': 'jof',
            'issn': '2309-608X',
        },
        'jof-crossref': {
            # https://www.mdpi.com/journal/jof
            'name': 'Journal of Fungi',
            'journal': 'journal-of-fungi',
            'address': 'https://www.mdpi.com/journal/jof',
            'source': 'crossref',
            'ingestor_class': 'CrossrefIngestor',
            'mode': 'api',
            'issn': '2309-608X',
            'mailto': 'piggy.yarroll+skol@gmail.com',
            'max_articles': None,  # None = all articles
            'allow_scihub': True,  # An OA journal.
        },
        'mycologie-crossref': {
            # https://sciencepress.mnhn.fr/en/articles/mycologie
            'name': 'Cryptogamie, Mycologie',
            'journal': 'cryptogamie-mycologie',
            'address': 'https://sciencepress.mnhn.fr/en/articles/mycologie',
            'source': 'crossref',
            'ingestor_class': 'CrossrefIngestor',
            'mode': 'api',
            'issn': '0181-1584',
            'mailto': 'piggy.yarroll+skol@gmail.com',
            'max_articles': None,  # None = all articles
            'allow_scihub': True,  # An OA journal.
        },
        'mycoscience-crossref': {
            # https://mycoscience.org/
            'name': 'Mycoscience: An open access journal of the Mycological Society of Japan',
            'journal': 'mycoscience',
            'address': 'https://mycoscience.org',
            'source': 'crossref',
            'ingestor_class': 'CrossrefIngestor',
            'mode': 'api',
            'issn': '1340-3540',
            'mailto': 'piggy.yarroll+skol@gmail.com',
            'max_articles': None,  # None = all articles
            'allow_scihub': True,  # An OA journal.
        },
        'mycologia-crossref': {
            # https://www.tandfonline.com/journals/umyc20
            'name': 'Mycologia (Taylor & Francis)',
            'journal': 'mycologia',
            'address': 'https://www.tandfonline.com/journals/umyc20',
            'source': 'crossref',
            'ingestor_class': 'CrossrefIngestor',
            'mode': 'api',
            'issn': '0027-5514',
            'mailto': 'piggy.yarroll+skol@gmail.com',
            'max_articles': None,  # None = all articles
            'allow_scihub': False,  # Not an OA journal.
        },
        'mycology-crossref': {
            # https://www.tandfonline.com/journals/tmyc20
            'name': 'Mycology: An International Journal on Fungal Biology (Taylor & Francis)',
            'journal': 'mycology',
            'address': 'https://www.tandfonline.com/journals/tmyc20',
            'source': 'crossref',
            'ingestor_class': 'CrossrefIngestor',
            'mode': 'api',
            'issn': '2150-1211',
            'mailto': 'piggy.yarroll+skol@gmail.com',
            'max_articles': None,  # None = all articles
            'allow_scihub': True,  # An OA journal.
        },
        # This source is not working at all.
        # 'oajmms-crossref': {
        #     # https://www.medwinpublishers.com/OAJMMS/
        #     'name': 'Open Access Journal of Mycology and Mycological Sciences',
        #     'source': 'crossref',
        #     'ingestor_class': 'CrossrefIngestor',
        #     'mode': 'api',
        #     'issn': '2689-7822',
        #     'mailto': 'piggy.yarroll+skol@gmail.com',
        #     'max_articles': None,  # None = all articles
        #     'allow_scihub': True,  # An OA journal.
        # },
        'mykoweb-journals': {
            'name': 'Mykoweb Journals (Mycotaxon, Persoonia, Sydowia)',
            'journal': None,  # Multiple journals
            'address': 'https://mykoweb.com/systematics/journals',
            'source': 'mykoweb-journals',
            'ingestor_class': 'LocalMykowebJournalsIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/systematics/journals',
            'local_path_prefix': '/data/skol/www/mykoweb.com/systematics/journals',
            'url_prefix': 'https://mykoweb.com/systematics/journals',
        },
        'mykoweb-literature': {
            'name': 'Mykoweb Literature/Books',
            'journal': None,  # Books, not a journal
            'address': 'https://mykoweb.com/systematics/literature',
            'source': 'mykoweb-literature',
            'ingestor_class': 'LocalMykowebLiteratureIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/systematics/literature',
            'local_path_prefix': '/data/skol/www/mykoweb.com/systematics/literature',
            'url_prefix': 'https://mykoweb.com/systematics/literature',
        },
        'mykoweb-caf': {
            'name': 'Mykoweb CAF PDFs',
            'journal': None,  # Collection, not a journal
            'address': 'https://mykoweb.com/CAF',
            'source': 'mykoweb-caf',
            'ingestor_class': 'LocalMykowebLiteratureIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/CAF',
            'local_path_prefix': '/data/skol/www/mykoweb.com/CAF',
            'url_prefix': 'https://mykoweb.com/CAF',
        },
        'mykoweb-crepidotus': {
            'name': 'Mykoweb Crepidotus',
            'journal': None,  # Collection, not a journal
            'address': 'https://mykoweb.com/Crepidotus',
            'source': 'mykoweb-crepidotus',
            'ingestor_class': 'LocalMykowebLiteratureIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/Crepidotus',
            'local_path_prefix': '/data/skol/www/mykoweb.com/Crepidotus',
            'url_prefix': 'https://mykoweb.com/Crepidotus',
        },
        'mykoweb-oldbooks': {
            'name': 'Mykoweb Old Books',
            'journal': None,  # Books, not a journal
            'address': 'https://mykoweb.com/OldBooks',
            'source': 'mykoweb-oldbooks',
            'ingestor_class': 'LocalMykowebLiteratureIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/OldBooks',
            'local_path_prefix': '/data/skol/www/mykoweb.com/OldBooks',
            'url_prefix': 'https://mykoweb.com/OldBooks',
        },
        'mykoweb-gsmnp': {
            'name': 'Mykoweb GSMNP',
            'journal': None,  # Collection, not a journal
            'address': 'https://mykoweb.com/GSMNP',
            'source': 'mykoweb-gsmnp',
            'ingestor_class': 'LocalMykowebLiteratureIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/GSMNP',
            'local_path_prefix': '/data/skol/www/mykoweb.com/GSMNP',
            'url_prefix': 'https://mykoweb.com/GSMNP',
        },
        'mykoweb-pholiota': {
            'name': 'Mykoweb Pholiota',
            'journal': None,  # Collection, not a journal
            'address': 'https://mykoweb.com/Pholiota',
            'source': 'mykoweb-pholiota',
            'ingestor_class': 'LocalMykowebLiteratureIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/Pholiota',
            'local_path_prefix': '/data/skol/www/mykoweb.com/Pholiota',
            'url_prefix': 'https://mykoweb.com/Pholiota',
        },
        'mykoweb-misc': {
            'name': 'Mykoweb Misc',
            'journal': None,  # Misc collection, not a journal
            'address': 'https://mykoweb.com/misc',
            'source': 'mykoweb-misc',
            'ingestor_class': 'LocalMykowebLiteratureIngestor',
            'mode': 'local',
            'local_path': '/data/skol/www/mykoweb.com/misc',
            'local_path_prefix': '/data/skol/www/mykoweb.com/misc',
            'url_prefix': 'https://mykoweb.com/misc',
        },
        'mycosphere': {
            'name': 'Mycosphere',
            'journal': 'mycosphere',
            'address': 'https://mycosphere.org',
            'source': 'mycosphere',
            'ingestor_class': 'MycosphereIngestor',
            'mode': 'web',
            'archives_url': 'https://mycosphere.org/archives.php',
        },
        'oajmms': {
            'name': 'Open Access Journal of Mycology & Mycological Sciences',
            'journal': 'open-access-journal-of-mycology-mycological-sciences',
            'address': 'https://www.medwinpublishers.com/OAJMMS',
            'source': 'medwin-publishers',
            'ingestor_class': 'MedwinPublishersIngestor',
            'mode': 'web',
            'archives_url': 'https://www.medwinpublishers.com/OAJMMS/archive.php',
            'issn': '2689-7822',
            'journal_name': 'Open Access Journal of Mycology & Mycological Sciences',
        },
        'mycokeys': {
            'name': 'MycoKeys: A peer reviewed open access journal',
            'journal': 'mycokeys',
            'address': 'https://mycokeys.pensoft.net',
            'source': 'pensoft',
            'ingestor_class': 'PensoftIngestor',
            'mode': 'web',
            'journal_name': 'mycokeys',
            'journal_id': '11',
            'issues_url': 'https://mycokeys.pensoft.net/issues',
            'issn': '1314-4057',
            'eissn': '1314-4049',
            'rate_limit_min_ms': 1000,
            'rate_limit_max_ms': 5000,
            'download_xml': True,
        },
        'imafungus': {
            'name': 'IMA Fungus: The Global Mycological Journal',
            'journal': 'ima-fungus',
            'address': 'https://imafungus.pensoft.net',
            'source': 'pensoft',
            'ingestor_class': 'PensoftIngestor',
            'mode': 'web',
            'journal_name': 'imafungus',
            'journal_id': '132',
            'issues_url': 'https://imafungus.pensoft.net/issues',
            'issn': '2210-6340',
            'eissn': '2210-6359',
            'download_xml': True,
        },
        'mycology-taylor-francis': {
            # Currently blocked by technical measures at tandfonline.com.
            'blocked': True,
            'name': 'Mycology (Taylor & Francis)',
            'journal': 'mycology',
            'address': 'https://www.tandfonline.com/loi/tmyc20',
            'source': 'mycology-taylor-francis',
            'ingestor_class': 'TaylorFrancisIngestor',
            'mode': 'web',
            'archives_url': 'https://www.tandfonline.com/loi/tmyc20',
            'journal_name': 'Mycology',
            'issn': '2150-1203',
            'eissn': '2150-1211',
        },
        'sydowia-ia': {
            'name': 'Sydowia (Internet Archive)',
            'journal': 'sydowia',
            'address': 'https://archive.org/details/pub_sydowia',
            'source': 'internet-archive',
            'ingestor_class': 'InternetArchiveIngestor',
            'mode': 'web',
            'collection': 'pub_sydowia',
            'download_xml': True,
            'issn': '0082-0598',
            'rate_limit_min_ms': 2000,
            'rate_limit_max_ms': 5000,
        },
        'jmycology-ia': {
            'name': 'Journal of Mycology (Internet Archive)',
            'journal': 'journal-of-mycology',
            'address': 'https://archive.org/details/jstor_jmycology',
            'source': 'internet-archive',
            'ingestor_class': 'InternetArchiveIngestor',
            'mode': 'web',
            'collection': 'jstor_jmycology',
            'download_xml': True,
            'issn': '1052-0368',
            'rate_limit_min_ms': 2000,
            'rate_limit_max_ms': 5000,
        },
    }

    @classmethod
    def get_all(cls) -> Dict[str, Dict[str, Any]]:
        """
        Get all publication source configurations.

        Each configuration includes default values merged with source-specific settings.

        Returns:
            Dictionary mapping publication keys to their configurations
        """
        result = {}
        for key, config in cls.SOURCES.items():
            cfg = cls.DEFAULTS.copy()
            cfg.update(config)
            result[key] = cfg
        return result

    @classmethod
    def get(cls, key: str) -> Optional[Dict[str, Any]]:
        """
        Get a specific publication configuration by key.

        Configuration includes default values merged with source-specific settings.

        Args:
            key: Publication key (e.g., 'mycotaxon', 'mycosphere')

        Returns:
            Publication configuration dict, or None if not found
        """
        config = cls.SOURCES.get(key)
        if config is None:
            return None
        cfg = cls.DEFAULTS.copy()
        cfg.update(config)
        return cfg

    @classmethod
    def get_robots_url(cls, source: str, custom_url: Optional[str] = None) -> str:
        """
        Get the robots.txt URL for a given source.

        Args:
            source: Name of the data source (e.g., 'ingenta', 'mycosphere')
            custom_url: Custom robots.txt URL (overrides default)

        Returns:
            URL to robots.txt file, or empty string if not found
        """
        if custom_url:
            return custom_url

        return cls.ROBOTS_URLS.get(source, '')

    @classmethod
    def list_publications(cls) -> list[str]:
        """
        Get a list of all available publication keys.

        Returns:
            Sorted list of publication keys
        """
        return sorted(cls.SOURCES.keys())

    @classmethod
    def get_defaults(cls) -> Dict[str, Any]:
        """
        Get default configuration values.

        Returns:
            Dictionary of default configuration values
        """
        return cls.DEFAULTS.copy()

    @classmethod
    def get_by_journal(cls, journal_name: str) -> Optional[Dict[str, Any]]:
        """
        Get the first publication configuration for a journal.

        Used to match documents (which have a 'journal' field that may
        still carry an old display name like 'Journal of Fungi (PMC)' or
        the canonical 'Journal of Fungi') to their source configuration.
        Post-refactor, ``SOURCES[*].journal`` is a slug FK into JOURNALS;
        this method resolves ``display_name → canonical_name → slug →
        first SOURCES entry pointing at that slug``.

        Args:
            journal_name: The journal name from a document (e.g.,
                'Mycotaxon', 'Journal of Fungi (PMC)',
                'Persoonia - Molecular Phylogeny and Evolution of Fungi')

        Returns:
            Publication configuration dict, or None if not found
        """
        slug = cls._find_slug_for_journal_name(journal_name)
        if slug is None:
            return None
        for key, config in cls.SOURCES.items():
            if config.get('journal') == slug:
                cfg = cls.DEFAULTS.copy()
                cfg.update(config)
                cfg['key'] = key  # source key for reference
                return cfg
        return None

    @classmethod
    def _find_slug_for_journal_name(
        cls, journal_name: str,
    ) -> Optional[str]:
        """Resolve a (possibly compound or aliased) journal display
        name to its canonical slug.  Order:

        1. Direct slug match (caller passed the slug itself).
        2. ``normalize_journal_name`` (strip publisher suffix +
           legacy alias resolution) → display-name lookup in JOURNALS.
        """
        if not journal_name:
            return None
        if journal_name in cls.JOURNALS:
            return journal_name
        canonical = cls.normalize_journal_name(journal_name)
        for slug, entry in cls.JOURNALS.items():
            if entry.get('name') == canonical:
                return slug
        return None

    @classmethod
    def get_journal(
        cls, slug_or_name: str,
    ) -> Optional[JournalEntry]:
        """Look up a JOURNALS entry by slug, display name, or known
        alias.

        Args:
            slug_or_name: One of:
                - a JOURNALS slug (``'sydowia'``);
                - a canonical display name (``'Sydowia'``);
                - a known alias (``'Sydowia Beih.'``) — resolved via
                  ``normalize_journal_name``.

        Returns:
            The JOURNALS entry, or None if the input doesn't resolve.
        """
        slug = cls._find_slug_for_journal_name(slug_or_name)
        if slug is None:
            return None
        return cls.JOURNALS[slug]

    @classmethod
    def find_journal_by_issn(
        cls, issn: Optional[str],
    ) -> Optional[str]:
        """Find the JOURNALS slug for a given ISSN (matches either the
        primary ``issn`` field or the ``eissn`` field).  Returns None
        for empty input or no match."""
        if not issn:
            return None
        for slug, entry in cls.JOURNALS.items():
            if entry.get('issn') == issn or entry.get('eissn') == issn:
                return slug
        return None

    @classmethod
    def find_journal_by_doi(
        cls, doi: Optional[str],
    ) -> Optional[str]:
        """Find the JOURNALS slug whose journal-level ``doi`` field
        matches.  Per-article DOIs are out of scope — those need a
        Crossref lookup, not a JOURNALS scan.  Returns None for empty
        input or no match."""
        if not doi:
            return None
        for slug, entry in cls.JOURNALS.items():
            if entry.get('doi') == doi:
                return slug
        return None

    @classmethod
    def find_journal_by_isbn(
        cls, isbn: Optional[str],
    ) -> Optional[str]:
        """Find the JOURNALS slug whose ``isbn`` field matches —
        used for book-like reference works (e.g. Funga Nordica
        chapters once they're registered in JOURNALS).  Returns None
        for empty input or no match."""
        if not isbn:
            return None
        for slug, entry in cls.JOURNALS.items():
            if entry.get('isbn') == isbn:
                return slug
        return None

    # Cache: ``{alias_value: canonical_name}`` index built from
    # every ``JOURNALS[*].aliases`` list on first call.
    _ALIAS_INDEX: Optional[Dict[str, str]] = None

    @classmethod
    def _build_alias_index(cls) -> Dict[str, str]:
        """Walk ``JOURNALS`` and flatten every entry's ``aliases``
        list into a ``{alias: canonical_name}`` lookup table.

        Cached on the class — invalidates only when the class is
        reloaded.  This is the post-phase-3 replacement for the
        legacy ``JOURNAL_NAME_ALIASES`` dict.
        """
        index: Dict[str, str] = {}
        for entry in cls.JOURNALS.values():
            canonical = entry.get('name')
            if not canonical:
                continue
            for alias in entry.get('aliases', []) or []:
                index[alias] = canonical
        return index

    @classmethod
    def normalize_journal_name(cls, journal_name: str) -> str:
        """
        Normalize a journal name to its canonical form.

        Two-step:
        1. Strip a known publisher-disambiguating parenthetical
           suffix (``" (PMC)"`` etc.) — see
           :func:`strip_publisher_suffix`.
        2. Scan ``JOURNALS[*].aliases``: if the stripped name
           matches an alias, return the owning journal's canonical
           ``name``.

        Args:
            journal_name: The journal name to normalize

        Returns:
            The canonical journal name (or the original if no
            normalization applies)
        """
        stripped = strip_publisher_suffix(journal_name)
        if cls._ALIAS_INDEX is None:
            cls._ALIAS_INDEX = cls._build_alias_index()
        return cls._ALIAS_INDEX.get(stripped, stripped)
